version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      apt-get install -y python-venv
      python3.8 -m venv test_venv
      . test_venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
  build:
    commands:
      python3.8 run.py