version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.6
  pre_build:
    commands:
      apt-get install -y python-venv
      python3.6 -m venv test_venv
      . test_venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
  build:
    commands:
      python3.6 run.py